### PR TITLE
Allow random ticks (and more) in chunk loader chunks in player proximity

### PR DESCRIPTION
**Pull request by flori-schwa**
The Mixin removed in this PR prevented calls to:
 - net.minecraft.world.chunk.Chunk#increaseInhabitedTime
 - net.minecraft.world.SpawnHelper#spawn and
 - net.minecraft.server.world.ServerWorld#tickChunk

inside the net.minecraft.server.world.ServerChunkManager#tickChunks method,  thus preventing the following in all chunks loaded by kibe, even if players were nearby:
 - Increase of InhabitedTime (Local Difficulty)
 - Mob spawning
 - Ice and Snow generation
 - Random Ticking (Crops growing, leaf decay, ...)

The vanilla behavior of canTickChunk already checks for player proximity, I'm not sure what the initial purpose of this Mixin was, but it was creating some confusion on our modded SMP world.

This behaviour was also submitted as a bug in lucaargolo/kibe#120

### CODE REVIEW

**Comment by lucaargolo** [comment]
Heyy, IIRC the purpose of this mixin is to allow random ticks in chunk-loaded chunks without the need of the player being nearby. At least that was it on 1.16/1.17. I know it's broken on 1.18 but I haven't got the time to fix it yet.

**Comment by flori-schwa** [comment]
In that case the return value only needs to be changed from false to true

**Comment by lucaargolo** [comment]
Yeah, looks like the logic got inverted on 1.18, before that it used to return if the player was too far for it to tick.

**Comment by lucaargolo** [comment]
All chunk loader issues should be fixed in the latest 1.9.5 release! This PR is no longer needed.

**Pull request closed without merging**
